apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "job-manager.fullname" . }}
  labels:
    {{- include "job-manager.labels" . | nindent 4 }}  
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: "test:latest"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["wait-for-it.sh"]
        args: [{{ .Values.grafanaService | quote }}]