apiVersion: v1
kind: Service
metadata:
  labels:
    app: traefik
  name: traefik-ui
  namespace: kube-system
spec:
  ports:
  - name: 80-80
    nodePort: 30080
    port: 8011
    protocol: TCP
    targetPort: 9000
  selector:
    app.kubernetes.io/name: traefik
  type: NodePort

